group: edge
dist: trusty

language: node_js
node_js:
  - 6
  - 7
  - 8

install: true
before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true

  # yarn
  - npm i -g yarn npm-check-updates node-gyp

script:
  - yarn -i
  - docker-compose -f docker/docker-compose-all.yml up -d --build
  - http post :3000/api/v1/message ololo=trololo
  - sleep 1
  - docker logs docker_message-command_1
  - docker-compose -f docker/docker-compose-all.yml down -v

after_install: cat *.log | true

cache:
  directories:
    - node_modules/
