version: "3.3"
services:
  mongo:
    restart: unless-stopped
    image: healthcheck/mongo:latest
    environment:
      MONGO_PORT_27017_TCP_PORT: 27017
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
  mongo-express:
    restart: unless-stopped
    depends_on: [mongo]
    image: mongo-express:0.42.2
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: guest
      ME_CONFIG_BASICAUTH_PASSWORD: guest
    ports: ["8081:8081"]
  rabbitmq:
    image: 127.0.0.1:5000/rabbitmq-healthcheck
    restart: unless-stopped
    build: ./rabbitmq-healthcheck
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes: ["rabbitmq-data:/var/lib/rabbitmq"]
  message-store:
    image: 127.0.0.1:5000/message-store
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    build:
      context: ../
      dockerfile: ./docker/message-store/Dockerfile
    environment:
      MONGODB_HOST: mongo
      RABBITMQ_HOST: rabbitmq
      MESSAGE_STORE_PORT: 3002
    volumes: ["message-store-data:/home/node/app"]
    ports: ["3002:3002"]
  message-command:
    image: 127.0.0.1:5000/message-command
    restart: unless-stopped
    depends_on: [rabbitmq]
    build:
      context: ../
      dockerfile: ./docker/message-command/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      MESSAGE_COMMAND_PORT: 3001
    volumes: ["message-command-data:/home/node/app"]
    ports: ["3001:3001"]
  message-frontend:
    image: 127.0.0.1:5000/message-frontend
    restart: unless-stopped
    depends_on: [message-command]
    build:
      context: ../
      dockerfile: ./docker/message-frontend/Dockerfile
    environment:
      MESSAGE_FRONTEND_PORT: 3000
      MESSAGE_COMMAND_HOST: message-command
    volumes: ["message-frontend-data:/home/node/app"]
    ports: ["3000:3000"]
volumes:
  mongo-data: {}
  rabbitmq-data: {}
  message-store-data: {}
  message-command-data: {}
  message-frontend-data: {}
